"""Ajout du statut dossier CRM

Revision ID: 07cf7aa81375
Revises: 
Create Date: 2026-03-26 17:25:10.376816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07cf7aa81375'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('statut_dossier', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operation', schema=None) as batch_op:
        batch_op.drop_column('statut_dossier')

    # ### end Alembic commands ###
