"""caisse_complete

Revision ID: 174e10770f3d
Revises: 
Create Date: 2026-04-21 20:54:43.900853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174e10770f3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parametre_tv', schema=None) as batch_op:
        batch_op.alter_column('borne_active_qr',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('borne_active_impression',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parametre_tv', schema=None) as batch_op:
        batch_op.alter_column('borne_active_impression',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('borne_active_qr',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###
